server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keep?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5

mybatis:
  type-aliases-package: com.example.keep.entity
  mapper-locations: classpath:mapper/*Mapper.xml

pagehelper:
  reasonable: true
  support-methods-arguments: true
  helper-dialect: mysql